bindPort = 4000
transport.tcpMux = false

[auth]
method = "token"
token = "{{ .Envs.SERVER_TOKEN }}"

[webServer]
port = 4001
addr = "0.0.0.0"
user = "{{ .Envs.SERVER_DASHBOARD_USERNAME }}"
password = "{{ .Envs.SERVER_DASHBOARD_PASSWORD }}"
