---
- name: Install k3s cluster
  ansible.builtin.import_playbook: site.yml
- name: Install helm on the control plane node
  hosts: server[0]
  become: true
  roles:
    - helm
- name: Install Cilium
  ansible.builtin.import_playbook: ../cilium/cli-install.yml
- name: Set up TLS certificates
  ansible.builtin.import_playbook: ../tls/cloudflare.yml
- name: Install Tailscale operator
  ansible.builtin.import_playbook: ../tailscale/operator.yml
