- name: Setup Critical cluster services
  hosts: server[0]
  become: false
  gather_facts: false
  tasks:
    - name: Run Traefik dashboard tasks
      include_role:
        name: k3s
        tasks_from: traefik-dashboard

    - name: Run Kubernetes dashboard tasks
      include_role:
        name: k3s
        tasks_from: k8s-dashboard

    - name: Setup Keel dashboard tasks
      include_role:
        name: k3s
        tasks_from: keel
