- name: Install Docker and Docker Compose
  hosts: k3s_cluster
  become: true
  vars:
    # configure users to be added to the docker group
    docker_users:
      - "{{ ansible_user | default('ubuntu') }}"
  roles:
    - role: geerlingguy.docker
