serverAddr = "frps-canopy"
serverPort = 7000

[auth]
method = "token"
token = "{{ .Envs.SERVER_TOKEN }}"

[[proxies]]
name = "frps-dashboard-stcp"
type = "stcp"
secretKey = "{{ .Envs.SERVER_DASHBOARD_SECRET_KEY }}"

localIP = "frps-canopy"
localPort = 7500
