ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.42.0.0/16

ingressController:
  enabled: false

l7Proxy: false

hubble:
  relay:
    enabled: false
  ui:
    enabled: false
