---
- name: Install Cilium using CLI
  ansible.builtin.command:
    cmd: >
      cilium install
      --set ipam.operator.clusterPoolIPv4PodCIDRList="10.42.0.0/16"
      --set ingressController.enabled=false
      --set l7Proxy=false
      --set hubble.relay.enabled=false
      --set hubble.ui.enabled=false
      --set MTU=1450
  delegate_to: localhost
  run_once: true
