apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: node
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("wallet-node.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node
          port: 50000
    - match: Host("explorer-node.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node
          port: 50001
    - match: Host("rpc-node.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node
          port: 50002
    - match: Host("admin-rpc-node.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node
          port: 50003
