apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: main
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("wallet-1.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node
          port: 50000
    - match: Host("explorer-1.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node
          port: 50001
    - match: Host("rpc-node-1-canopy.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node
          port: 50002
    - match: Host("admin-rpc-node-1-canopy.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node
          port: 50003
