apiVersion: v1
kind: Namespace
metadata:
  name: servarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: servarr
  name: radarr
  labels:
    app: radarr
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      nodeSelector:
        type: secondary
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          ports:
            - containerPort: 7878
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: data
              mountPath: /data/media
            - name: config
              mountPath: /config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: servarr
  name: sonarr
  labels:
    app: sonarr
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      nodeSelector:
        type: secondary
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          ports:
            - containerPort: 8989
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: data
              mountPath: /data/media
            - name: config
              mountPath: /config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: servarr
  name: prowlarr
  labels:
    app: prowlarr
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      nodeSelector:
        type: secondary
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: data
              mountPath: /data/media
            - name: config
              mountPath: /config
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          env:
            - name: LOG_LEVEL
              value: "info"
        - name: gluetun
          image: qmcgaw/gluetun:latest
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            privileged: true
          envFrom:
            - secretRef:
                name: gluetun
          ports:
            - containerPort: 8191
              name: flaresolverr
            - containerPort: 9696
              name: prowlarr
          env:
            - name: TZ
              value: Etc/UTC
            - name: VPN_TYPE
              value: wireguard
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/15"
            - name: FIREWALL_VPN_INPUT_PORTS
              value: "9696,8191"
            - name: FIREWALL_INPUT_PORTS
              value: "9696,8191"
              # volumeMounts:
              #   - name: gluetun-config
              #     mountPath: /gluetun
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: servarr
  name: bazarr
  labels:
    app: bazarr
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:latest
          ports:
            - containerPort: 6767
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: data
              mountPath: /data/media
            - name: config
              mountPath: /config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: bazarr-config-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: servarr
  name: monitarr
  labels:
    app: monitarr
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitarr
  template:
    metadata:
      labels:
        app: monitarr
    spec:
      nodeSelector:
        type: main
      containers:
        - name: monitarr
          image: ghcr.io/nickshanks347/monitarr:latest
          ports:
            - containerPort: 3000
          env:
            - name: SONARR_URL
              value: "http://sonarr:8989"
            - name: SONARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: monitarr
                  key: SONARR_API_KEY
                  optional: false
            - name: RADARR_URL
              value: "http://radarr:7878"
            - name: RADARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: monitarr
                  key: RADARR_API_KEY
                  optional: false
