apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: servarr
  name: radarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: radarr
          port: 7878
    - match: Host(`prowlarr.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: prowlarr
          port: 9696
    - match: Host(`sonarr.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: sonarr
          port: 8989
    - match: Host(`bazarr.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: bazarr
          port: 6767
    - match: Host(`monitarr.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: monitarr
          port: 80
