apiVersion: v1
kind: Secret
metadata:
  name: longhorn-frontend
  namespace: longhorn
type: Opaque
stringData:
  users: "remini:$apr1$oNmfVmzk$rqXmzlsT6GPr7bc4XOLUv1"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: longhorn
spec:
  basicAuth:
    secret: longhorn-frontend
    removeHeader: true
---
kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: longhorn-frontend
  namespace: longhorn
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.{{ DOMAIN }}`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
      middlewares:
        - name: auth
          namespace: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: longhorn
  name: longhorn-lb
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8200
      protocol: TCP
      targetPort: http
  selector:
    app: longhorn-ui
