# global configuration
appName: it-tools
ports:
  - 80
domain: it-tools

# deployment configuration
deployment:
  name: it-tools
  nodeSelector:
    type: pi
  containers:
    - name: it-tools
      image: ghcr.io/sharevb/it-tools:latest
      ports:
        - 8080

# service configuration
svc:
  ports:
    - port: 80
      targetPort: 8080

# ingress configuration
ingress:
  routes:
    - services:
        - name: "it-tools"
          port: 80
