apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: canopy

resources:
  - ../../../base

components:
  - ../../../components/chain-1
  - ../../../components/shared

nameSuffix: -main-1

labels:
  - pairs:
      app: node-main-1
    includeSelectors: true

patches:
  - path: config-map.yml
    target:
      kind: ConfigMap
      name: node
  - patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          type: vm
      - op: replace
        path: /spec/template/spec/initContainers/0/volumeMounts/0/subPath
        value: node-main-1
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/0/subPath
        value: node-main-1
      - op: replace
        path: /spec/template/spec/containers/1/volumeMounts/0/subPath
        value: node-main-1
    target:
      kind: Deployment
      name: node
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host("wallet-node-main-1.{{DOMAIN}}")
      - op: replace
        path: /spec/routes/1/match
        value: Host("explorer-node-main-1.{{DOMAIN}}")
      - op: replace
        path: /spec/routes/2/match
        value: Host("rpc-node-main-1.{{DOMAIN}}")
      - op: replace
        path: /spec/routes/3/match
        value: Host("admin-rpc-node-main-1.{{DOMAIN}}")
    target:
      kind: IngressRoute
      name: node
