tailscale:
  authkey: <tailscale_authkey>
docker:
  watchtower:
    discord:
      webhook_id: <discord_webhook_id>
      token: <discord_token>
tls:
  cloudflare_token: <cloudflare_token>
  email: <email>
  domain: <domain>
