docker:
  tailscale:
    token: <tailscale-token>
  watchtower:
    discord_webhook_url: <watchtower-token>
# hosts:
#   "192.168.0.91":
#     watchtower:
#       discord_webhook_url: "https://discord.com/api/webhooks/xxx/nuc-webhook"
#   "192.168.0.98":
#     watchtower:
#       discord_webhook_url: "https://discord.com/api/webhooks/xxx/amd-webhook"
#   "192.168.0.88":
#     watchtower:
#       discord_webhook_url: "https://discord.com/api/webhooks/xxx/pi2-webhook"
#   "192.168.0.86":
#     watchtower:
#       discord_webhook_url: "https://discord.com/api/webhooks/xxx/pi3-webhook"
#   "188.245.61.138":
#     watchtower:
#       discord_webhook_url: "https://discord.com/api/webhooks/xxx/vm-webhook"
