# enable insecure registries
insecureRegistry: true

# custom polling schedule (default: @every 1m)
polling:
  defaultSchedule: "@every 1h"

# basic auth on approvals
basicauth:
  enabled: true
  user: remini
  password: hhd3qFDd

# enable keel service to receive webhooks from Docker registries
service:
  enabled: true

# keel self-update
keel:
  policy: all
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repository
      tag: image.tag

# persistence
persistence:
  enabled: true
  storageClass: "longhorn-local"
  size: 1Gi
